//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doAnChuyenNghanh02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_HDNHAP
    {
        public int IDCTN { get; set; }
        public int IDSP { get; set; }
        public int SOLUONG { get; set; }
        public Nullable<int> IDHDNHAP { get; set; }
    
        public virtual HOADONNHAP HOADONNHAP { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
