//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doAnChuyenNghanh02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHITIET_DONTHANG
    {
        public int IDCTDONHANG { get; set; }
        public int IDSP { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public Nullable<int> TONGTIEN { get; set; }
        public Nullable<int> IDDONHANG { get; set; }
    
        public virtual DONHANG DONHANG { get; set; }
        public virtual SANPHAM SANPHAM { get; set; }
    }
}
