//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doAnChuyenNghanh02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DONHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DONHANG()
        {
            this.CHITIET_DONTHANG = new HashSet<CHITIET_DONTHANG>();
        }
    
        public int IDDONHANG { get; set; }
        public Nullable<System.DateTime> NGAYDAT { get; set; }
        public string TRANGTHAI { get; set; }
        public Nullable<int> IDTKNV { get; set; }
        public Nullable<int> IDTKKH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONTHANG> CHITIET_DONTHANG { get; set; }
        public virtual TAIKHOANKHACHHANG TAIKHOANKHACHHANG { get; set; }
        public virtual TAIKHOANNHANVIEN TAIKHOANNHANVIEN { get; set; }
    }
}
