//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doAnChuyenNghanh02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HOADONNHAP
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HOADONNHAP()
        {
            this.CHITIET_HDNHAP = new HashSet<CHITIET_HDNHAP>();
        }
    
        public int IDHDNHAP { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string TRANGTHAI { get; set; }
        public string GHICHU { get; set; }
        public Nullable<int> IDTKNV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDNHAP> CHITIET_HDNHAP { get; set; }
        public virtual TAIKHOANNHANVIEN TAIKHOANNHANVIEN { get; set; }
    }
}
