//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace doAnChuyenNghanh02.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SANPHAM
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SANPHAM()
        {
            this.CHITIET_DONTHANG = new HashSet<CHITIET_DONTHANG>();
            this.CHITIET_HDNHAP = new HashSet<CHITIET_HDNHAP>();
            this.OrderDetails = new HashSet<OrderDetail>();
        }
    
        public int IDSP { get; set; }
        public string TENSP { get; set; }
        public string MOTA { get; set; }
        public Nullable<int> GIA { get; set; }
        public Nullable<int> SOLUONG { get; set; }
        public string ANHSP { get; set; }
        public string IDNCC { get; set; }
        public Nullable<int> IDDM { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_DONTHANG> CHITIET_DONTHANG { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIET_HDNHAP> CHITIET_HDNHAP { get; set; }
        public virtual DANHMUC DANHMUC { get; set; }
        public virtual NHACUNGCAP NHACUNGCAP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual SANPHAMMOI SANPHAMMOI { get; set; }
    }
}
